### ISSUE TITLE
mvn install fail on TwitterCrawlerTests since March1st commits

### ISSUE THREAD

**Issue by nodje** [kbastani/twitter-graph-analytics#6]
FYI `TwitterCrawlerTests` fails on a "clean" `mvn install` after cloning the project.
I don't know if it works on Travis as the commited work points to, but it doesn't locally.

Original error seem to be:

```
18:26:48.581 [main] INFO  c.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
18:26:48.799 [main] ERROR c.n.d.s.t.d.RedirectingEurekaHttpClient - Request execution error
com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: discovery: unknown error
```

**Comment by kbastani** [comment]
Thanks. Fixed in https://github.com/kbastani/spring-boot-graph-processing-example/commit/347275fb26769e9e8b62daafb78a03b229472f43

**Comment by nodje** [comment]
I guess there's still a problem with the new `org.kbastani.TwitterCrawlerTests`

It fails with the message:
`INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [org.kbastani.TwitterCrawlerTests]: no resource found for suffixes {-context.xml, Context.groovy}.`

**Comment by nodje** [comment]
It's the Spring profiles annotations that cause it not to find its resources.
If you remove `@ActiveProfiles("test")` and `@IfProfileValue(name = "test")` the test starts fine.

I'm not too sure why you put them here but I don't think you need them, you just need to activate `-Dspring.profiles.active=test` when you run the test. 

But then you have another problem. You can't really do integration test on the crawler without starting other components. Even if you manage deactivate Spring Cloud in the test profile (I guess this is what 
`eureka.client.enabled: false` is about) you still need to have a Neo4j&AMQP instance.

They could be launched by the maven-docker-plugin, but I don't know if it can do that. Otherwise it'd be needed to mock these dependencies, but then you can only partially test the crawler.
I guess it's complex enough to deserve a few tests.

Again, I'm just trying to guess here, as I have no idea how you planned this test.
